version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - .:/src
    ports:
      - 4002:4002
    env_file:
      - .env
    depends_on:
      - postgresql

  
volumes:
  postgres-db: {}



