version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    restart: always
    environment:
      - PGUSER=$POSTGRES_USER
      - PGHOST=$POSTGRES_HOSTNAME
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
    

  api:
    build: .
    volumes:
      - .:/src
    ports:
      - 4002:4002
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
  
volumes:
  postgres-db: 



