"""update recipes table with image file path column

Revision ID: 969a5b9b30fb
Revises: e0590c32187f
Create Date: 2023-04-01 15:49:57.769032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969a5b9b30fb'
down_revision = 'e0590c32187f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_file_path')
    # ### end Alembic commands ###
