"""update user and image relationship and user_id fk type

Revision ID: c369dc1fd7dd
Revises: efebe2175d4f
Create Date: 2023-05-20 13:27:33.031779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c369dc1fd7dd'
down_revision = 'efebe2175d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'images', 'user', ['user_id'], ['id'])
    op.drop_constraint('profile_photo', 'user', type_='foreignkey')
    op.drop_column('user', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('profile_photo', 'user', 'images', ['photo_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
