"""update recipes table with calories column

Revision ID: e0590c32187f
Revises: 3252bafff0b0
Create Date: 2023-03-29 19:09:05.264098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0590c32187f'
down_revision = '3252bafff0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'calories')
    # ### end Alembic commands ###
