"""Added images table

Revision ID: efebe2175d4f
Revises: c40b688fcab8
Create Date: 2023-05-16 11:56:20.825583

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'efebe2175d4f'
down_revision = 'c40b688fcab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create images table
    op.create_table('images',
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Add user Profile Photo
    op.add_column('user', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key("profile_photo", 'user', 'images', ['photo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_photo", 'user', type_='foreignkey')
    op.drop_column('user', 'photo_id')
    op.drop_table('images')
    # ### end Alembic commands ###
